
import { SparePart } from '../types';

// Generate mock spare parts
export const mockSpareParts: SparePart[] = [
  {
    id: 'pt-001',
    name: 'Copper Cap Tip',
    partNumber: 'CCT-5000',
    partType: 'cap-tip',
    description: 'High conductivity copper cap tip for standard welding applications',
    compatibleRobots: ['FANUC', 'ABB', 'KUKA'],
    manufacturer: 'WeldTech',
    supplier: 'Industrial Welding Supplies',
    unitPrice: 24.99,
    stockQuantity: 45,
    minStockLevel: 20,
    reorderPoint: 25,
    reorderQuantity: 50,
    location: 'Warehouse A, Shelf B3',
    leadTime: 7,
    lastOrdered: '2023-08-15',
    lastRestocked: '2023-08-22',
    status: 'in-stock',
    notes: 'High-wear component, needs frequent replacement'
  },
  {
    id: 'pt-002',
    name: 'Standard Tip Base',
    partNumber: 'STB-3000',
    partType: 'tip-base-moving',
    description: 'Standard tip base compatible with most cap tips',
    compatibleRobots: ['FANUC', 'ABB', 'KUKA'],
    manufacturer: 'WeldTech',
    supplier: 'Industrial Welding Supplies',
    unitPrice: 89.99,
    stockQuantity: 18,
    minStockLevel: 10,
    reorderPoint: 15,
    reorderQuantity: 20,
    location: 'Warehouse A, Shelf C2',
    leadTime: 10,
    lastOrdered: '2023-09-10',
    lastRestocked: '2023-09-20',
    status: 'in-stock',
    notes: 'Medium-wear component'
  },
  {
    id: 'pt-003',
    name: 'Heavy Duty Shank',
    partNumber: 'HDS-7500',
    partType: 'shank-moving',
    description: 'Reinforced shank for high-pressure welding applications',
    compatibleRobots: ['FANUC', 'KUKA'],
    manufacturer: 'RoboWeld',
    supplier: 'RoboWeld Direct',
    unitPrice: 159.99,
    stockQuantity: 8,
    minStockLevel: 5,
    reorderPoint: 7,
    reorderQuantity: 10,
    location: 'Warehouse B, Shelf A1',
    leadTime: 14,
    lastOrdered: '2023-10-05',
    lastRestocked: '2023-10-19',
    status: 'in-stock',
    notes: 'Low-wear component, check for cooling line integrity'
  },
  {
    id: 'pt-004',
    name: 'Universal Adapter',
    partNumber: 'UA-2000',
    partType: 'adapter-moving',
    description: 'Universal adapter compatible with multiple robot makes',
    compatibleRobots: ['FANUC', 'ABB', 'KUKA', 'Yaskawa'],
    manufacturer: 'RoboWeld',
    supplier: 'RoboWeld Direct',
    unitPrice: 129.50,
    stockQuantity: 3,
    minStockLevel: 2,
    reorderPoint: 3,
    reorderQuantity: 5,
    location: 'Warehouse B, Shelf B4',
    leadTime: 21,
    lastOrdered: '2023-11-01',
    status: 'low-stock',
    notes: 'Check compatibility with robot model before installation'
  },
  {
    id: 'pt-005',
    name: 'Heavy Duty Adapter',
    partNumber: 'HDA-5000',
    partType: 'adapter-fixed',
    description: 'Reinforced adapter for high-stress welding applications',
    compatibleRobots: ['FANUC', 'KUKA'],
    manufacturer: 'WeldTech',
    supplier: 'Industrial Welding Supplies',
    unitPrice: 199.99,
    stockQuantity: 0,
    minStockLevel: 1,
    reorderPoint: 2,
    reorderQuantity: 3,
    location: 'Warehouse A, Shelf D1',
    leadTime: 30,
    lastOrdered: '2023-11-10',
    status: 'on-order',
    notes: 'Critical component for high-volume production lines'
  },
  {
    id: 'pt-006',
    name: 'Extended Reach Cap Tip',
    partNumber: 'ERCT-8000',
    partType: 'cap-tip',
    description: 'Extended length cap tip for hard-to-reach weld points',
    compatibleRobots: ['FANUC', 'ABB'],
    manufacturer: 'WeldTech',
    supplier: 'Industrial Welding Supplies',
    unitPrice: 34.99,
    stockQuantity: 22,
    minStockLevel: 10,
    reorderPoint: 12,
    reorderQuantity: 25,
    location: 'Warehouse A, Shelf B4',
    leadTime: 7,
    lastOrdered: '2023-09-25',
    lastRestocked: '2023-10-02',
    status: 'in-stock',
    notes: 'Prone to bending under high pressure'
  },
  {
    id: 'pt-007',
    name: 'Offset Tip Base',
    partNumber: 'OTB-4000',
    partType: 'tip-base-fixed',
    description: 'Offset design for angled welding applications',
    compatibleRobots: ['FANUC', 'ABB', 'KUKA'],
    manufacturer: 'RoboWeld',
    supplier: 'RoboWeld Direct',
    unitPrice: 109.99,
    stockQuantity: 5,
    minStockLevel: 3,
    reorderPoint: 4,
    reorderQuantity: 8,
    location: 'Warehouse B, Shelf C1',
    leadTime: 10,
    lastOrdered: '2023-10-18',
    lastRestocked: '2023-10-28',
    status: 'in-stock',
    notes: 'Verify angle requirements before installation'
  },
  {
    id: 'pt-008',
    name: 'Articulating Shank',
    partNumber: 'AS-6000',
    partType: 'shank-fixed',
    description: 'Flexible shank for complex weld geometries',
    compatibleRobots: ['ABB', 'KUKA'],
    manufacturer: 'RoboWeld',
    supplier: 'RoboWeld Direct',
    unitPrice: 259.99,
    stockQuantity: 0,
    minStockLevel: 1,
    reorderPoint: 1,
    reorderQuantity: 2,
    location: 'Warehouse B, Shelf A2',
    leadTime: 28,
    lastOrdered: '2023-11-05',
    status: 'out-of-stock',
    notes: 'Special order item, requires engineering approval'
  },
  {
    id: 'pt-009',
    name: 'KUKA-Specific Adapter',
    partNumber: 'KSA-9000',
    partType: 'adapter-fixed',
    description: 'Adapter specifically designed for KUKA robots',
    compatibleRobots: ['KUKA'],
    manufacturer: 'RoboWeld',
    supplier: 'RoboWeld Direct',
    unitPrice: 179.99,
    stockQuantity: 4,
    minStockLevel: 2,
    reorderPoint: 3,
    reorderQuantity: 5,
    location: 'Warehouse B, Shelf B3',
    leadTime: 14,
    lastOrdered: '2023-08-20',
    lastRestocked: '2023-09-03',
    status: 'in-stock',
    notes: 'Only compatible with KUKA robots'
  },
  {
    id: 'pt-010',
    name: 'High-Conductivity Cap Tip',
    partNumber: 'HCCT-7000',
    partType: 'cap-tip',
    description: 'Premium copper-alloy cap tip for high-current applications',
    compatibleRobots: ['FANUC', 'ABB', 'KUKA', 'Yaskawa'],
    manufacturer: 'WeldTech',
    supplier: 'Industrial Welding Supplies',
    unitPrice: 45.99,
    stockQuantity: 15,
    minStockLevel: 10,
    reorderPoint: 12,
    reorderQuantity: 25,
    location: 'Warehouse A, Shelf B2',
    leadTime: 10,
    lastOrdered: '2023-10-08',
    lastRestocked: '2023-10-18',
    status: 'in-stock',
    notes: 'Recommended for high-amperage welding'
  }
];
